title: Visio-Azure
description: A modern, searchable Visio stencil set for Microsoft Azure. 1,259 icons. Working shape search. Connection points. Shape data.
theme: jekyll-theme-cayman
baseurl: /Visio-Azure
url: https://xeeva.github.io
show_downloads: false
